# SOPS configuration
# Replace AGE_PUBLIC_KEY with your actual age public key (age1...)

creation_rules:
  - path_regex: \.yaml$
    age: "age1faajkhjhavuj4qljnfm4u7yt2pc7kfzvu5kxx5q2780635yl0alsqgglj2"
